### ISSUE TITLE
Portal Shader Stretched on iPad

### ISSUE THREAD

**Issue by calben** [pr0g/unity-portal-rendering#2]
Heya,

When compiled for iOS 11 metal, this shader is a bitch stretched on an iPad.
Anybody know why?

Cheers!

**Comment by danpilat** [comment]
Having same issue. Appreciate any help!

**Comment by Sekoul** [comment]
Same here...

**Comment by pr0g** [comment]
Oh interesting... Hmm I'm afraid I don't have any idea off of the top of my head... I forget but is it possible to deploy to an iPad on macOS in Unity without a Unity or iOS developer license? A pro license that is... if not I can try and repro it at the weekend and see what is wrong. Could you grab a screen shot to show what it looks like? Perhaps it's to do with the aspect ratio not being handled correctly... totally guessing right now

**Comment by calben** [comment]
Ah I missed your super quick reply!  I think it recently became possible to deploy without a pro license, but I haven't done it yet.  I'm going to be devoting a bit of time to this problem today though.

I've uploaded a screenshot here:

![https://i.imgur.com/DBwlenb.jpg](https://i.imgur.com/DBwlenb.jpg)

**Comment by pr0g** [comment]
No worries! Okay cool I'll see if I can repro it later this week, hopefully tomorrow (maybe today if I get time). I'm probably doing something dumb with the screen aspect, I'll see if there's anything obvious. I wonder if it happens when doing a normal build to desktop when you make a standalone app, I'll give that a try too.

**Comment by pr0g** [comment]
Hey there, I tried reproing this by doing a normal build on macOS but it seemed okay - currently updating Unity, iOS, macOS etc. etc... as I haven't looked at this in a while, it does look like I'll be able to deploy though, will try and update tomorrow if I find anything.

**Comment by pr0g** [comment]
Hello again... okay so I have managed to update everything and get to building, but I'm getting an error saying - App installation failed - Could not write to the device - when attempting to deploy from XCode - I've tried restarting my device but didn't have much luck, is there some dumb thing I'm missing? Cheers!

**Comment by calben** [comment]
I'll ask the iOS dude! Sometimes this happens if you already have an application with the same name deployed?

**Comment by pr0g** [comment]
Nah don't think it's that... Hmm I'll try again in a bit, if you have any ideas/things to try, give me a shout, cheers!

**Comment by pr0g** [comment]
Sorry I've been rubbish at finding time to look into this... I was thinking it might be because I'm not explicitly setting the view frustum somewhere, and it works serendipitously on desktop as the defaults work, but in iOS not so much, I'll try and repro again this weekend, if you had any other luck/ideas let me know! Cheers!

**Comment by pr0g** [comment]
Okay did some more digging and I believe it's related to this issue - https://forum.unity.com/threads/render-to-texture-forcing-aspect-ratio-change-on-camera.7072/

Notably the camera.aspect bit. I still haven't been able to repro as Xcode was being hopeless last time I tried. I'll see if I can look into it but that advice above definitely seems worth a try.

**Comment by JoshRobbinsPixo** [comment]
Did any one manager to solve this issue yet?

**Comment by BlackMirrorz** [comment]
For anyone interested I was able to fix this issue by setting the Portal Camera Aspect Ratio to that of the MainCamera e.g:
portalCamera.aspect = mainCamera.aspect.

**Comment by pr0g** [comment]
Hey BlackMirrorz,

That's awesome! I don't suppose you could create a PR with your fix I could merge in? (or just let me know what file/line you updated and I can make the change myself and push).

I did start trying to look at this yesterday but to deploy to my iPad I needed up update XCode, but to do that I needed to update macOS, but then I couldn't do that as I have a bootcamp partition :weary:

I'm trying to just scrap my bootcamp partition and finally see if I can actually repro this, but failing that your fix sounds good, thanks for the info!

Cheers,


Tom

**Comment by pr0g** [comment]
Hey there,

Update on this issue! 😄- I've FINALLY been able to get this demo building on my iPad and encountered an issue with how the portals were displayed. This appeared to be an issue in the shader where I was using `UNITY_UV_STARTS_AT_TOP` - it turns out I also needed to check `_MainTex_TexelSize.y < 0` per the Unity docs...

Apologies for the massive delay - I haven't updated the `aspect` yet as from my limited testing it didn't seem like this was causing a problem for me (maybe this got fixed in a later version of Unity? I'm not sure...) I'm going to update the CameraController to make it easier to fly around on iOS to double check if it's required or not.

I'd be grateful if people could check out the update and see if it resolves the problem they were seeing. If so I'll close out this Issue.

Thanks!


Tom
